# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20171124_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='fecha',
        ),
    ]
